### ISSUE TITLE
Tie together all the work done on the echochamber/echosign repos

### ISSUE THREAD

**Issue by joelbarker2011** [joelbarker2011/echosign#1]
There are a bunch of forks of [kayagoban/echochamber](https://github.com/kayagoban/echochamber) out there. The goal of this repo is to bring all the improvements together into one place, work collaboratively, involve whichever developers are active, and push out a gem to RubyGems as needed.

- [x] Invite key developers from the forks to contribute (done w/r/t @kayagoban, @bernardworthy, @LupusDei, @benjaminkeeping, @orignaux, and @abimaelmartell).
- [x] Clone a repo to use as a base (I chose [SilkFred/echosign](https://github.com/SilkFred/echosign), because it brings in all of @bernardworthy's work, as well as some fixed some syntax errors).
- [x] Create an initial gem and push to RubyGems (mostly in order to claim the `echosign` gem name).
- [x] Merge improvements from the other forks.

**Comment by kayagoban** [comment]
This seems like a good idea.  I likely won't be a collaborator but I applaud the effort, and BTW shout out to @bernardworthy for updating this to v5.  Glad that some form of this has survived.

**Comment by joelbarker2011** [comment]
Thanks so much for starting this, @kayagoban. I've been using it for a couple of years now, and clearly other folks are too. :clap:
